--vim.keymap.set('n', '<C-k>', ':wincmd k<CR>')
--vim.keymap.set('n', '<C-j>', ':wincmd j<CR>')
--vim.keymap.set('n', '<C-h>', ':wincmd h<CR>')
--vim.keymap.set('n', '<C-l>', ':wincmd l<CR>')
--
--vim.keymap.set('n', '<leader>sv', '<cmd>vsp<CR>')
--vim.keymap.set('n', '<leader>sh', '<cmd>sp<CR>')
--
--vim.keymap.set('n', '<leader>w', '<cmd>q<CR>')
