# yazi.toml
[mgr]
show_hidden = true

[plugin]
prepend_previewers = [
  { url = "*.csv", run = "bat" },
  { url = "*.json", run = "bat" },
  { url = "*.md", run = "bat" },
	  
  { mime = "text/*",                 run = "bat" },
  { mime = "text/csv",                 run = "bat" },
    { mime = "*/xml",                  run = "bat" },
	{ mime = "*/cs",                   run = "bat" },
	{ mime = "*/javascript",           run = "bat" },
	{ mime = "*/x-wine-extension-ini", run = "bat" },
]
